apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: heartbeat
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./clusters/lab01/heartbeat/base
  prune: true
  dependsOn:
    - cert-manager
  sourceRef:
    kind: GitRepository
    name: gitops
