apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./releases/cert-manager/1.16.1
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops
