apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-listeners
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/lab01/flux-listeners
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops
