# Default values for heartbeat
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: heartbeat
nameOverride: heartbeat
fullnameOverride: heartbeat
uri: /heartbeat

image:
  repository: ghcr.io/cse-labs/heartbeat
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "0.4.0"

env:
  Namespace: heartbeat
  Application: heartbeat
  TITLE: Heartbeat
  URI: /heartbeat
  Region: Lab
  State: TX
  City: Austin
  Ring: lab

service:
  type: ClusterIP
  port: 8080

livenessProbe:
  httpGet:
    path: /heartbeat/healthz
    port: http
